### ISSUE TITLE
Building a multiplayer game server and keeping (most of) your hair

### ISSUE THREAD

**Issue by OpherV** [nodeconf/budapest#13]
**Title**

Building a multiplayer game server and keeping (most of) your hair

**Description**

Whether it’s a first person shooter, real time strategy, action or physics based - making a game is the hardest software challenge you will ever undertake. That is - until you’ve decided to make it multiplayer. 

So how do you create a server that runs a game, communicates with clients and compensates for lag? How do you make all your players feel like they’re playing the same game, at the same time, with each other (even though they actually don’t)?

I will present the major challenges for enabling low-latency games on the web with with Node.js. I’ll also talk about how to write efficient net code, optimize the data that goes over the wire and demystify scary terms like “client side prediction” and “entity interpolation/extrapolation”.  
By the end of the talk you’ll have a working multiplayer game that we can all play together!

**Learning objectives**
- Understanding the challenges of real-time, low-latency games
- Solutions to problems of latency and perception
- Why Node is awesome for making games on the web

**City of Residence**
Tel Aviv, Israel

**Comment by gergelyke** [comment]
Hi Opher!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
