### ISSUE TITLE
NodeGirls or how attract women for IT events

### ISSUE THREAD

**Issue by ButenkoT** [nodeconf/budapest#14]
#### Title

NodeGirls or how attract women for IT events
#### Description

Nowadays everyone talks about diversity in IT and why we don't have enough women. Every time I hear this discussions the only solutions are coming up is to make IT attractive for girls from childhood, encourage girls-teenagers etc. It is a good solution but in a long term. But is there anything we can do in a short-term?

I by myself started programming 2.5 years ago with self-guided tutorials, online courses and occasional workshops. Now I work as a full stack javascript/node developer and mentor in Sydney. I'm also co-organiser of WomenWhoCode in Sydney, co-organiser of Nasa Space Apps Challenge, organiser of NodeSchool workshops and a founder of NodeGirls Sydney (upcoming Melbourne and Brisbane). 

Having organised and hosted a bunch of IT events for the last year I learned a lot about diversity and I would be happy to share that knowledge with others.
#### Learning objectives
- Encourage women to join, participate, mentor and organise IT events 
- Share experience on how to organise high-diversity events, hackathons, workshops 
#### City of residence

Sydney, Australia

**Comment by gergelyke** [comment]
Hello Tanya!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!

**Comment by ButenkoT** [comment]
Thank you for reply.

I will try to make it for conference and also feel free to reach me out in the future, as next year I plan to be in Europe 1 or 2 times.
