### ISSUE TITLE
The Dark Side of Observables

### ISSUE THREAD

**Issue by hrajchert** [nodeconf/budapest#15]
#### Title

The Dark Side of Observables
#### Description

Reactive Functional Programming is the new kid in the block, everyone loves it, and so do I. It provides a different way to think about async, and it's a key component to provide smooth experiences, that's why Netflix promotes it, and Angular 2 have RxJs as one of its 4 dependencies. 

But like most things, the devil is in the details. Instead of doing Yet Another Observable Talk, providing the selling points, the silver bullets, I decided to take out the dirty laundry, see what are the things to look out for, the gotchas, and what are the things I wish I had known before starting out.
#### Learning objectives
- Learn common pitfalls when using Rx
- Understand how FP relates to Rx
#### City of residence

Buenos Aires

**Comment by gergelyke** [comment]
Hi Herman!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
