### ISSUE TITLE
Enhancing Node command line apps with Bash

### ISSUE THREAD

**Issue by JuanCaicedo** [nodeconf/budapest#16]
#### Title

Enhancing Node command line apps with Bash
#### Description

Imagine being able to build simple scripts that can interact easily with any
Unix commands and compose together to make complex applications. Not only is
that possible with Node.js, it's easy! Node provides easy access to everything
you need to create powerful system-level utilities, and following the Unix
philosophy of modularity and reusability enables developers to write
incredibly powerful and flexible command line applications. This talk will
introduce the concepts of Unix command pipelines, input and output stream
handling in Node.js, and effective API design for Node scripts. By the end,
developers will know how to begin writing custom scripts that hook up to any
other Unix utilities.
#### Learning objectives
1. Pass data from bash utilities to Node scripts and back out
2. Write Node scripts that can be tested on small jobs yet used for large jobs 
3. Show bash isn't hard or scary, and any Node dev can leverage it! 
#### City of residence

Medellín, Colombia

**Comment by gergelyke** [comment]
Hi Juan!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
