### ISSUE TITLE
RxJS - destroy the state machine!

### ISSUE THREAD

**Issue by stenver** [nodeconf/budapest#19]
#### Title

RxJS - destroy the state machine!
#### Description

Learn our story how we discovered RxJS and it helped to bring us from a massive state machine into an elegant event-based reactive platform. In this talk I am going to give you an overview of RxJS and why should you use it. I am going to talk about how once we adopted the reactive approach, it completely changed the way we think about state and state programming. All this with code examples.
#### Learning objectives

RxJS, Reactive programming
#### City of residence

Estonia, Tartu

**Comment by gergelyke** [comment]
Hey!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
