### ISSUE TITLE
Design for Non-Designers

### ISSUE THREAD

**Issue by tracymakes** [nodeconf/budapest#20]
#### Title

Design for Non-Designers
#### Description

Not everyone can hire a professional designer for their websites and web apps, but we all still want our interfaces to be easy to use and attractive. However, if you want to learn a bit of design, design books jump straight into concepts like "the golden ratio" and teach proper typographic terms which, to be frank, aren't needed if you're just looking to improve your website's look and feel.

This talk will cover the top quick ways to improve your website, covering both user experience as well as visual design. Quick hits, easy to understand and utilize principles that anyone can use to improve their design skills. Perhaps you too can become the next designer+developer unicorn!
#### Learning objectives

Attendees should have the know-how to quickly improve the design of their websites immediately as well as knowledge of resources to improve their design eye.
#### City of residence

Toronto, ON Canada

**Comment by gergelyke** [comment]
Hello Tracy!

Closing this as your other submission was selected!
