### ISSUE TITLE
PM2

### ISSUE THREAD

**Issue by Unitech-access** [nodeconf/budapest#23]
### Description

PM2 is **the most advanced and used process manager of the Node.js ecosystem**. With **14k+** stars on [Github](https://github.com/Unitech/pm2), **50k** downloads/day and 12M in total now, it is one of the most starred package of npm. We are about to launch a new version very adapted to the new era of microservices and that's why we communicate this year. Also, we are launching a new research OS project called [Gridcontrol](https://github.com/gridcontrol/gridcontrol) related to P2P cloud function that could, if good traction, skyrocket some features of PM2 and other back-end applications.
### Learning objectives
- Microservices architecture
- Load balancing, process management, performance and monitoring issues
### City of residence

*France/Paris

**Comment by gergelyke** [comment]
Hey!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!

**Comment by Unitech** [comment]
I never applied to NodeConf Budapest, I don't know this Unitech-access account.
