### ISSUE TITLE
NodeJS Testing: The Most Efficient Approach

### ISSUE THREAD

**Issue by lucasfcosta** [nodeconf/budapest#24]
#### Title

NodeJS Testing: The Most Efficient Approach
#### Description

If your goal with tests is to prove your software has no bugs, you are doing it wrong. In this 20 minute talk I will not only show you why this approach is bad, I will show you how to write better tests with the newest available tools. I won’t talk about TDD, I will talk about doing it right.

Efficacy means being able to get something done, but efficiency means being able to get something done in the best way possible, and that is what I’m going to talk about.

Almost everybody know what is TDD and how it is done, but not many people know how to write tests right and, unfortunately, this makes the whole process lose its value. Let me show you why getting this right can save you a lot of time and save your company a lot of money, if you have never thought about the correlation between those two factors you better prepare to be astonished.

In this talk I will show you solid facts and examples to convince you how important it is to write good tests, what is the most efficient mindset to have when writing tests and why the metrics most people use to measure the effectiveness of their tests are wrong.

Come with me and I guarantee the quality of the code you and your team are delivering will never be the same. Test things right: more time available, less bugs on production.
#### Learning objectives
- TDD
- Better Unit Testing
- Assertion/Testing Libraries in NodeJS
#### City of residence

**Florianópolis** - Brazil

**Comment by gergelyke** [comment]
Hey Lucas!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
