### ISSUE TITLE
Conflict Resolution with Guns

### ISSUE THREAD

**Issue by amark** [nodeconf/budapest#25]
#### Title

Conflict Resolution with Guns
#### Description

How do you survive failure? You distribute. But distributed systems are distressingly complicated, everything from PAXOS to RAFT. Can we do better? Can we simplify things while still achieving reasonable results? And how do you handle conflict without a Master?

We'll demonstrate some amazing recoveries from harsh failures and go into detail about how the fully Open Source, peer-to-peer distributed algorithm works. We'll also discuss its weaknesses, where it fits in the CAP Theorem, and how it can be used as a building block for higher level consistency guarantees.
#### Learning objectives

You'll learn why Master based algorithms like PAXOS and RAFT have so many edge cases, and why Masterless alternatives are better - excluding certain limitations. You'll come out of the talk with a fresh perspective on concurrency that will help you make better decisions for your company's tough distributed problems and why graphs help solve them.
#### City of residence

Los Angeles or Salt Lake City

**Comment by gergelyke** [comment]
Hello Mark!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
