### ISSUE TITLE
Debugging Node.js Performance Issues in Production

### ISSUE THREAD

**Issue by watson** [nodeconf/budapest#26]
#### Title

Debugging Node.js Performance Issues in Production
#### Description

Node.js doesn’t require much to get started building apps. You can easily create a simple HTTP server, query a database and respond to client requests. But as with any other platform, sooner or later you’ll run into issues like scalability, memory leaks, or requests that take forever to complete.

This talk covers the top Node.js performance issues, and will guide you through how to solve them.
#### Learning objectives

Learn how to detect, debug and fix performance issue with your Node.js application
#### City of residence

Copenhagen, Denmark

**Comment by gergelyke** [comment]
Hello Thomas!

Closing this one as your other submission was selected!
