### ISSUE TITLE
Node Todo: Making Everyone A Contributor

### ISSUE THREAD

**Issue by Trott** [nodeconf/budapest#28]
#### Title

Node Todo: Making Everyone A Contributor
#### Description

Node Todo is an initiative to have free and open-to-the-public events and resources to help people get their first (and second and third) commits into Node.js core. Lots of projects have labels in their issue trackers for “good first contributions” or “easy fixes". Those sorts of things often run into problems. Node Todo is an attempt to solve those problems, or at least an attempt to extend and improve the “good first contribution” label.

In any event, I'll just leave this right here: http://nodetodo.org/
#### Learning objectives

Why is it important to evangelize contributing?
And what has and hasn't worked?
And how can you get involved? 
#### City of residence

San Francisco

**Comment by gergelyke** [comment]
Hey Rich!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
