### ISSUE TITLE
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Serverless Chatbots

### ISSUE THREAD

**Issue by stojanovic** [nodeconf/budapest#29]
#### Title

Dr. Strangelove or: How I Learned to Stop Worrying and Love the Serverless Chatbots
#### Description

A talk about what could happen if the wrong person combine multiple buzzwords and press the wrong button -- and it played the situation for laughs.  
The main goal of this talk is to analyze 2 different and at the moment popular buzzwords - serverless and chatbots; and then to combine them with node.js and simple NLP and show how easy is to build useful chatbots with insignificant cost of the infrastructure. 
#### Learning objectives
- What is "serverless" and why and for what it makes sense
- Why and for what chatbots can be useful
- How to build a serverless chatbot with a simple NLP that costs $0
#### City of residence

Belgrade, Serbia

**Comment by gergelyke** [comment]
Hey Slobodan!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
