### ISSUE TITLE
Use Promise, Future and some functional programing stuff without being a math nerd.

### ISSUE THREAD

**Issue by waxzce** [nodeconf/budapest#30]
#### Title

Use Promise, Future and some functional programing stuff without being a math nerd.
#### Description

Javascript is awesome, and asynchronous. But some libraries are made by egocentric people : how to contain all DB interaction to the connection callback? Does the Callback soup a fatality? This talk help you to use data structure to keep safe your code. Some great ideas are coming from the functional programming world. How to use it with javascript browser and/or node.js? Is it really complicated?
So, Future, Promise, Either, Options and other algebraic data model can be useful, there is how
#### Learning objectives

I write this talk because I use node.js a lot and write a lot of fix in my code to abstract database driver (couchbase, mongo, postgre...). I found an effective way to solve problems using functional programing data structure. But this talk is not for nerd or claiming functional programing superiority : some tools are cool, make your code cleanest and modular, so use it !

http://fr.slideshare.net/quentinadam/use-promise-future-and-some-functional-programing-stuff-without-being-a-math-nerd-devoxx-maroc-2015
#### City of residence

Nantes, France

**Comment by gergelyke** [comment]
Hey Quentin!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
