### ISSUE TITLE
Sex, Lies and Design Patterns

### ISSUE THREAD

**Issue by rubystream** [nodeconf/budapest#31]
#### Title

Sex, Lies and Design Patterns
#### Description

Almost everyone in software industry agrees that design patterns are important and beneficial for success of any project. Some regard them as an essential part of ‘good practices”.

On the other hand, more in the land of reality, most development efforts are done under various pressures, from vague specifications, short schedules, ridiculous time to market constraints and similar. As a result what is called good practices usually suffer and get substitute with just practices, or less.

There are numerous excuses reported by various developers why the design patterns are only consequence of implementation instead of deliberate action of software architecture design in their projects.

It's totally bizarre to not use the tool whose main purpose is to show success path in order to solve the encountered problem. It’s even more strange as we know that all of design patterns come out of experience and long process of real life validation.

Knowledge to recognize the problem, the context and to pick appropriate design / action patterns are essential for creating any worth mentioning solution.

This talk will try to emphasize need to keep design patterns continuously in focus during software development efforts but also how to distinct good ones from hype.
#### Learning objectives
- what is sex and how it's related to design patterns
- what are lies related to design patterns
- the grand scheme of design patterns, what, when, why
#### City of residence

Belgrade, Serbia

**Comment by gergelyke** [comment]
Hello Dejan,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
