### ISSUE TITLE
The Hitchhiker's Guide to Serverless

### ISSUE THREAD

**Issue by southpolesteve** [nodeconf/budapest#32]
#### Title

The Hitchhiker's Guide to Serverless
#### Description

"Serverless". It is already being called the buzzword of 2016. Steve is going to bring "serverless" back to reality by showing how Bustle has built a fully serverless application platform. Real production examples handling millions of API calls a day. You will leave knowing if the hype is justified.
#### Learning objectives

This talk is not just about explaining what serverless is. I'll do a little of that, but I want to unpack "serverless" with concrete examples. At Bustle were doing ~15 million serverless API calls a day. Several of our applications are completely end to end serverless. I'll talk about how we use it, where it has been awesome, where it has fallen down. I want attendees to leave with a understanding of what a building a real production serverless platform is like. I want to give them a real foundation of knowledge that could be used to justify building serverless apps to clients/PMs/CTOs and also non-technical colleagues.
#### City of residence

Philadelphia, USA

**Comment by mxstbr** [comment]
Not sure if this is appropriate, but Steve is a great speaker. Definitely knows what he's talking about. (totally unsolicited, btw, found this by accident while checking on my own submission)

**Comment by southpolesteve** [comment]
thanks @mxstbr 😄 😄

**Comment by gergelyke** [comment]
Sadly Steve cannot make it :(
