### ISSUE TITLE
Demystifying NaN, Infinity, and Floating Point Numbers

### ISSUE THREAD

**Issue by LewisJEllis** [nodeconf/budapest#33]
#### Title

Demystifying NaN, Infinity, and Floating Point Numbers
#### Description

You’ve probably seen `NaN` and `Infinity` pop up on you before, but do you really know the when & why? We’ll go through what these two values are, where they appear, and what one should know about them, from the perspectives of JavaScript and floating point numbers. Then a quick primer on floating point binary representations will take us into numbers so big that `x + 1 === x`. We'll use Node Buffers to first see how those numbers behave and how big they can get, and then to count just how many `NaN`s there really are. This goes all the way down to the ECMA-262 and IEEE 754 specs and covers quirks, gotchas, and some history of how we got to where we are. Some parts will verge on esoteric, but only enough to get a good laugh and see how numbers really work.
#### Learning objectives

No longer be afraid of `NaN`, `Infinity`, and floating point numbers. Understand why:
- `NaN !== NaN`
- `1 ** Infinity` should equal `Infinity ** 0` but doesn’t
- `2 ** 53` equals `2 ** 53 + 1`
- `1.8e308` equals `Infinity` but `1.79e308` doesn’t
#### City of residence

San Francisco

This would be an expansion of a ~12 minute talk on NaN I gave at [WaffleJS](http://wafflejs.com/) in May 2016. The slides for that talk are [here](https://speakerdeck.com/lewisjellis/idiosyncrasies-of-nan-v2) and a video recording is [here](https://www.youtube.com/watch?v=GeM22aTO4Ks).

**Comment by gergelyke** [comment]
Hello Lewis!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
