### ISSUE TITLE
Yaks, Lambdas, and first class citizens on nodejs

### ISSUE THREAD

**Issue by ferakpeter** [nodeconf/budapest#34]
#### Title

Yaks, Lambdas, and first class citizens on nodejs
#### Description

The talk covers the history of computational theory and how it applies to modern programming languages. Kurt Gödel's incompleteness theorem, Alonzo Church's Lambda Calculus, and Haskell Curry-Howard isomorphism are described in terms of what it meant for Computing. However, the talk is about modern (ES6) Javascript and how those concepts can be used within any node.js program. It's very interactive as I will be using a node-REPL throughout the talk to demonstrate the concepts with small code chunks. 

Javascript contains lots of functional elements out of the box, and I will explains how you can leverage those concepts to structure your programs more concisely while making your syntax easier to understand and more declarative. 

The talk is extending a short session I did earlier this year: https://youtu.be/nzOb1kNVrZQ
#### Learning objectives

Structuring a program with functions and leveraging immutability, Better understanding the State of your app, REPL-driven development
#### City of residence

Vienna, Austria

**Comment by gergelyke** [comment]
Hey there!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
