### ISSUE TITLE
FullStack DevOps.

### ISSUE THREAD

**Issue by alexfernandez** [nodeconf/budapest#35]
#### Title

FullStack DevOps.
#### Description

JavaScript has long reigned in the frontend, and has in the past few years taken the backend by assult. It is high time we start making inroads at DevOps development. Many languages have thrived in the space: Java (Ant, Jenkins), Ruby (Puppet, Chef), Python (Ansible, Fabric), and now Go (Docker or Kubernetes). Luckily there are now some Node.js packages: StriderCD or ShipIt, but they are nowhere near the adoption that they should have.

In this talk we will speak about our real-world experience at MediaSmart Mobile using Node.js for DevOps. We have long used Node.js to create our own tools: load testing, deployment, server orchestration. We are now adopting third party packages like StriderCD and ShipIt, with mixed success. We will show how knowing how to build your own tools is important for any self-respecting engineer, and when to choose third party software. We will also explore the limits of JavaScript and Node.js, with practical cases: for instance how we [built our own balancer](http://alexfernandez.github.io/2016/nginx-balancer.html) that routinely handles 400k requests per second.
#### Learning objectives
- Use Node.js for DevOps work.
- Build your own infrastructure tools.
- Operational constraints of Node.js.
#### City of residence

Madrid, Spain.

**Comment by gergelyke** [comment]
Hey Alex!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
