### ISSUE TITLE
Using Node to unlock new input devices

### ISSUE THREAD

**Issue by AVGP** [nodeconf/budapest#37]
#### Description

There is new input devices coming to the market that let us use our hands or our full body to control the computer. But how do we get those devices to the browser?

The answer is: Node.js and web sockets!

In this talk we'll find out how to connect a LEAPMotion for magical hand-waving to command the computer, a Kinect to finally get some excercise and then look at the general concept of using node extensions to grab data from new hardware and pipe it into the browser using web sockets.

It'll be weird, it'll be fun and you'll see things you normally don't do in Node - luckily so.
#### Learning objectives
- Using and making C extensions for Node.js
- Using WebSockets to feed input device data to the browser
- What is OpenNI and how to use it with a Kinect device
#### City of residence

Zurich, Switzerland

**Comment by gergelyke** [comment]
Hello Martin!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
