### ISSUE TITLE
“I can’t work on my phone” - desktop all the things

### ISSUE THREAD

**Issue by stefanjudis** [nodeconf/budapest#38]
#### Title

“I can’t work on my phone” - desktop all the things
#### Description

The web platform gets stronger every month. Bluetooth, offline capability and even virtual reality are coming into our browsers.

Does this mean that we don't need desktop apps anymore?

No, a big trend is happening in parallel. A new go-to platform to build desktop applications entered the stage – Electron.

Everything in Electron is built with HTML, CSS and JavaScript. Now frontend developers build almost everything with it. From small tiny apps solving everyday problems to full fledged IDEs – developers build tools for the environment they spend at least eight hours a day in: the desktop.

Let's have a look at how this works and what it takes to build a desktop app from scratch.
#### Learning objectives

The audience will learn how to build Electron apps themselves. They will see that it doesn't take much more than a bit of JavaScript knowledge to build apps fitting exactly their needs and solving problems they have every day.
#### City of residence

Berlin

**Comment by gergelyke** [comment]
Hi Stefan!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
