### ISSUE TITLE
Building a VPN with node

### ISSUE THREAD

**Issue by mabels** [nodeconf/budapest#39]
#### Description

There are alot VPN solution out there. But all uses proprietary protocols for transport.
But we have web sockets why not pipe raw ip through this? And than allow to have a server running node and a client either running node too or just a browser.
I used a c++ part to attach the kernel routing the userlevel. But I had done this in plain node before in my sashimi project. 
#### Learning objectives

Websocket, Typescript, Tun/Tap, C++, Buffers, Streams
#### City of residence

Living on the Road

**Comment by gergelyke** [comment]
Hey Meno!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
