### ISSUE TITLE
Building chat bots with Node.js, Telegram example

### ISSUE THREAD

**Issue by PavloPoliakov** [nodeconf/budapest#4]
#### Title

Building chat bots with Node.js, Telegram example
#### Description

**What are the chat bots and why could chat bots become/becoming important right now?**
Basically, nobody is going to install your mobile app anymore, it's not convenient, people are fed with the number of mobile apps on their phones. If you are another pizza delivery - people would not install your app, however they can contact you via their favourite messaging platform.

**Which messaging platforms are allowing us to develop the chat bots?**
Facebook, Slack, Telegram, Microsoft Bot Framework (https://dev.botframework.com/)

_As Telegram provides the most richest API comparing to the other messaging platforms, further I'm going to focus crowd attention on developing for this platform._
**How to develop the chat bot? What do you need for local development, how to deploy your bot?**
- How to integrate unit and e2e testing of your bot?
  I expect it would be the biggest part of the section, where I want to share my experience in developing the Telegram bot.
  Currently you can find my opensource "[learning-germant-bot](https://github.com/PavelPolyakov/learning-german-bot)" on GitHub. During the development I have found a list of interesting things, which can make it easier to start bots development for others:
- Registering the bot with BotFather.
- Technologies used Hapi.js + MongoDb.
- Using https://ngrok.com/ for testing your bot locally.
- Using https://buddy.works/ (for free) for configuring of CI for your bot, not an advertisement, only my experience.
- unit and e2e tests

**Using storebot. Analytics for your bot?**
After the bot is ready to go live we can publish it to the Telegram's bot store. https://storebot.me/ .
It's already possible to track analytics for your bot, using http://botan.io/ .

**Even more interesting**
To make the presentation even more interesting, I suggest developing some custom opensource bot for the conference. Therefore during the presentation I will refer all the points to the BudapestNodeJsBot development process.
#### Learning objectives
- what are the chat bots, why do we need them, why it could be promising area to invest your time
- how to build a Telegram bot from A to Z
#### City of residence

Hamburg, Germany

**Comment by gergelyke** [comment]
Hello Pavel!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
