### ISSUE TITLE
Doing Network unittests with node

### ISSUE THREAD

**Issue by mabels** [nodeconf/budapest#40]
#### Title

Doing Network unittests with node
#### Description

For a giving ip network graph out of router and hosts, you want to be sure if.you change something is it still working like expected. The only way to do this is by building a system an see if it works. But would it.be nice if you are able.to write an unittests, where you validate if a packet passes a specific path and is not been dropped by any obstacles like firewalls.
#### Learning objectives

IP Routing,Javascriptobjectgraphs,Visualisation,Typescript
#### City of residence

Living on the Road

**Comment by gergelyke** [comment]
Hello Meno!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
