### ISSUE TITLE
Speed as a maximum priority with Node.js

### ISSUE THREAD

**Issue by quibusus** [nodeconf/budapest#41]
#### Title

Speed as a maximum priority with Node.js
#### Description

We all have tried Express, Hapi or other Node.js frameworks. They are awesome, but sometimes we need to use a custom solution to get the maximum out of our servers for a specific purpose.

I will show you how we use dedicated worker processes with ZeroMQ to push the limits of our severs further, how we ensure speedy responses even when our database layer gets grumpy, and why it is good to tell yourself how fast your system needs to be before you start coding.
#### Learning objectives
- Advantages of Worker pattern in Node.js
- Using ZeroMQ with Node.js
- Tips for speed-oriented applications
#### City of residence

Prague, Czech Republic

Video pitch https://www.youtube.com/watch?v=j7CXtsfI-2o

**Comment by gergelyke** [comment]
Hi Karol!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
