### ISSUE TITLE
You Too Can Be A Sketching Machine!

### ISSUE THREAD

**Issue by rizwanjavaid** [nodeconf/budapest#43]
#### Title

You Too Can Be A Sketching Machine!
#### Description

Sketching is a crucial skill for all Adobe Creative Cloud users.  Whether you use Photoshop, Illustrator, After Effects, Premiere Pro or any other Adobe CC application, sketching can help while brainstorming ideas, iterating through concepts, and communicating our ideas to others. Whether working individually or in a group, our ability to sketch helps take the abstract ideas out of heads and into the real world. If you’re not comfortable sketching then there is little chance that your ideas will stick with you, your team members, and even your clients. Don’t worry—the confidence you need to put your pen to paper and start to sketch is close at hand! With the addition of a few simple approaches to your daily routine, you too can harness the power of sketching and become a sketching machine. 

Please bring a pen (Yes, pen. I will explain why in the presentation), a highlighter, a Post-It notepad, and a notebook. We will do some fun sketching activities so you can experience the power of sketching firsthand.
#### Learning objectives
- Learn the power of sketching
- Take part in various activities to see that everyone can sketch and that it doesn't take a lot of time.
- Gain confidence to harness the power of sketching.
- Get out of your comfort zone where the learning happens. 
#### City of residence

Roseville, California, USA

**Comment by gergelyke** [comment]
Hey!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
