### ISSUE TITLE
Transitions between Server Side Rendering and Client Side

### ISSUE THREAD

**Issue by evenstensberg** [nodeconf/budapest#44]
# Transitions between Server Side Rendering and Client Side
#### Description

Going from Client Side and Server Side rendering in Node is a big deal. Now, as most enterprise firms use Webpack, Babel, React while having their own API's, there is much ground to cover from Client Side to SSR. Complications are hard to reason about and to do server side rendering, it seems like people need to know the whole stack in order to profit from using this at all. 

The presentation will go through how you reason about the transition at a core level. Naturally, there will also be code covered in the talk while we go through improvement steps. We will try to make the transition as easy as possible on the technical side while reasoning on the pragmatic upsides and downsides of having SSR and when we should use it.
#### Learning objectives
- Give people the ability to write SSR code similarly to Client Side
- Give beginners the ground they'll need in order to do SSR
- Convince people how SSR could impact Development Flow
- Explain why implementation symmetry is important to workflow
#### City of residence

Oslo, Norway

**Comment by gergelyke** [comment]
Hello Even,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
