### ISSUE TITLE
Organising a conference - the coder way

### ISSUE THREAD

**Issue by JGAntunes** [nodeconf/budapest#45]
#### Title

Organising a conference - the coder way
#### Description

Managing an organisation is hard, organising a conference is hard, managing an organisation that organises conferences... Well you guessed it, it's even harder! This is the story of how we, a group of students involved in [SINFO](sinfo.org), came to build a set of open source tools and services in NodeJS to help us manage all of our events.

From the initial problems we aimed at solving, to the caffeine packed hack nights we spent coding insanely amounts of Javascript, to the wrong decisions we made, to where we are now. We’ll get a view of the back office we use to manage contacts, sponsors, speakers and the agenda for the events and how it fuels our web app, side by side with a service used to manage our attendees.
#### Learning objectives

This talk won’t present any new software design pattern, or a new tool that can improve the life of every developer. It will rather cover a set of software development steps we, as young developers/engineers/hackers, came to do or miss and how this helped us realise how important they are. This included the absence of tests that slowed us down, or how the cool project you hacked in a fortnight is suddenly used by a whole bunch of people and you’ve got no idea what you’re doing.
#### City of residence

Lisbon, Portugal

**Comment by gergelyke** [comment]
Hello Joao!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
