### ISSUE TITLE
From Zero to Hero IRL

### ISSUE THREAD

**Issue by akoskm** [nodeconf/budapest#46]
#### Title

From Zero to Hero IRL
#### Description

A year ago I quit my day job and founded my own company so I could pursue the technologies I find truly productive and innovative. Since then I’m building web applications for living.

How I delivered my first production-ready app with the help of NodeJS and user system starter platforms like Drywall, Aqua, Frame? How I deployed the first production updates and handled the first production issues?

In retrospect to the past year lots of things has been changed. I developed new coding habits, found better tools, adopted new technologies. Find out what triggered these changes.
#### Learning objectives

I won’t dive deeply into any particular technology I used, the documentations can be found online. What I will do is tell my first-hand experience of becoming a full-stack engineer with the help of NodeJS.

This talk can be helpful for those who want to start their own business or thinking about switching platforms. Those who spent years with JavaScript, learn how the current ecosystem looks like from the perspective of a newcomer.
#### City of residence

Novi Sad, Serbia

**Comment by gergelyke** [comment]
Hey Akos!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
