### ISSUE TITLE
Building Cross-Platform Desktop Applications With Electron

### ISSUE THREAD

**Issue by tanay1337** [nodeconf/budapest#47]
#### Title

Building Cross-Platform Desktop Applications With Electron
#### Description

The advent of web technologies and evolution of JavaScript has made web the first choice for running applications.Electron is the next-generation technology for developing desktop applications. It uses HTML, JavaScript and other web technologies to build the applications and Node.JS to hold it all together.Using Electron, you can develop applications once and run them multiple times, anywhere. Using Electron web developers, who are comfortable with JavaScript, HTML and other web technologies can develop high-performance cross platform desktop applications. 

This talk will cover all the aspects of desktop application development using Electron, starting from the basics to a deep dive into Electron as a technology. It will cover the basic application structure, installation procedure, the main process, renderer process, communication between processes using IPC, working with native menus, dialogs, UI toolkit for Electron like Photon and finally packaging of applications. The attendees will also be learning about the basics of Node.JS which is the building block of Electron.
#### Learning objectives
- Learn how to build desktop applications with Electron
- Main Process, Renderer Process
- Communication between the processes using IPC
- Using toolkits like Photon
- Packaging of the desktop applications built on Electron
#### City of residence

New Delhi

**Comment by gergelyke** [comment]
Hello Tanay,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
