### ISSUE TITLE
Node.js and Africa market

### ISSUE THREAD

**Issue by opeyOg** [nodeconf/budapest#48]
#### Title

Node.js and Africa market
#### Description

Faster Code vs Slow Internet: How useful Node.js could be for Africa market in performance? What does the Africa market look like? What the dev community in Africa knows about Node.js? Prudence OGATCHA will highlight opportunities and challenges and solutions for Node ecosystem in Africa. Prudence OGATCHA will discuss the new full stack and present how Pliby (https://pliby.com) is solving problems to address performance optimisation with the slower Africa internet, and the music streaming service.
#### Learning objectives

My presentation will be useful and profitable for all global scale enterprise, startup or node.js developer to efficiently target the Africa market. It will expose also the need for Node Foundation to empower and train developers in Africa for the benefit of Node.js ecosystem in Africa.
#### City of residence

Lagos, Nigeria

**Comment by gergelyke** [comment]
Hello Ogatcha!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!

**Comment by opeyOg** [comment]
Thank you for the decision and I understood.
I've as well appreciated the discount offer on the ticket and I'm
interested with that favour to be on the conference even as attendee.
I'm willing to pay the ticket but I have to get my visa ready before I can
make that investment on the ticket.

If you can get an official invitation letter as early as possible to me, I
can start the visa process now and as soon as my visa is okay I can pay the
ticket and prepare my trip.

Thank you!

Full name: OGATCHA FINAGNON PRUDENCE
Country of birth: BENIN REPUBLIC
Passport number: B0458334
Company:  PLIBY
Title:  JS/Node.js Developer
Phone number: +2349055553511
Address: Block B, Suit 170-172, Sura Complex, Simpson street Lagos, Lagos
101001, Nigeria
