### ISSUE TITLE
How much scaffolding do you need?

### ISSUE THREAD

**Issue by haack** [nodeconf/budapest#49]
#### Title

How much scaffolding do you need?
#### Description

It’s been widely discussed that, in the JavaScript universe, we have a paralysing abundance of tooling, frameworks, libraries, and packages (which also change every year). Often referred to as 'Javascript fatigue'

A useful question to ask is how much scaffolding and tooling do you need for what you are building?

I'd like to suggest an approach of starting with the minimal amount, and to iteratively add tools as you need to.

Loosely based on the article I have just published here: https://medium.com/@Haakathon/js-in-2016-how-much-scaffolding-do-you-need-bdbf857af766#.kb8kjji4q
#### Learning objectives
1. Learn what the problem is: JavaScript Fatigue
2. Learn what a useful solution is: Scaffolding iteratively
3. Walkthrough at an example application, starting with vanilla js and building up to a fully fledged universal web app.
#### City of residence

London

**Comment by gergelyke** [comment]
Hello Alex!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
