### ISSUE TITLE
Make Content Management Great Again

### ISSUE THREAD

**Issue by mxstbr** [nodeconf/budapest#5]
#### Title

Make Content Management Great Again
#### Description

Bringing the Node.js philosophy to content management gives us a new way to solve a perennial problem. Yesterday's CMS solved yesterday's problems; with Node.js we tackle the challenges of tomorrow.

Content management is a hard problem and one that everybody has. Users need a CMS, developers want an adaptive CMS. 3.5 million developers are going to use Node.js for the first time this year, and with Node.js everyone can have the CMS they deserve.

By combining Node.js' modularity, its package ecosystem, and modern development techniques we can challenge age old assumptions about developing with a CMS. We can break through the ceiling that traditional CMS platforms represent.

We can make content management great again!
#### Learning objectives
- The Node.js Philosophy, and why it matters
- How we took those ideas to create a completely new way to look at content management
- How you can use those ideas in your own work to create awesome things
#### City of residence

Vienna, Austria

**Comment by gergelyke** [comment]
Hey Max!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
