### ISSUE TITLE
BASH-ing tedious problems like a pro!

### ISSUE THREAD

**Issue by presmihaylov** [nodeconf/budapest#51]
#### Title

BASH-ing tedious problems like a pro!
#### Description

Do you find yourself doing repetitive tasks way too often?

Well, what I want to show you is how to write scripts, which would help you handle tedious tasks with ease. I will be using one of the most popular environments used in Linux distributions nowadays - bash, to teach you the basics of writing scripts. Apart from handling everyday work, the techniques we will discuss are applicable for other areas as well - whether you are a sysadmin, finding a way to automate your work, or a web developer maintaining a site.
#### Learning objectives

What a "shell" actually is (and I don't mean the tortoise kind of shell).
The basics of writing bash scripts and how to use them for common tasks.
When is it a good decision to rely on bash scripts for a given problem and when it is not.
#### City of residence

Sofia, Bulgaria

**Comment by gergelyke** [comment]
Hello Preslav,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
