### ISSUE TITLE
From Puny to Beast: the Cluster API in NodeJS

### ISSUE THREAD

**Issue by giltayar** [nodeconf/budapest#52]
#### Title

From Puny to Beast: the Cluster API in NodeJS
#### Description

Node's cluster api was built to handle NodeJS's inability to use more than one cpu at a time. Learn how, and learn what more we can do with this interesting API.

Yes, it will help you support multi-cpus in node, but it can also handle failure scenarios, help with memory management, and in general make your web app more robust. In the talk we will go in depth into this fascinating and magical api.

Slides: https://docs.google.com/presentation/d/1CqFze_UHzwSWcFGTemM9KhCwhbfhX8qIHct1voaVWI8
#### Learning objectives

How to use the Cluster apis for various scenarios - from the regular load balancing one, to the less familiar ones.
#### City of residence

Tel Aviv, Israel

**Comment by gergelyke** [comment]
Hello Gil,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
