### ISSUE TITLE
An Ode to Node: Testing Frontend the Backend Way

### ISSUE THREAD

**Issue by giltayar** [nodeconf/budapest#53]
#### Title

An Ode to Node: Testing Frontend the Backend Way
#### Description

Testing Frontend code is painful. You can either do small unit tests that don't check a lot, or you have to use automation tools to test your code in a living browser.

There is a third alternative, which can be a very natural way to test your code - run your frontend code under Node!

The benefits are enormous - simple debugging, no need for transpiling and bundling, and no need to raise a server to run the tests., all of which give for an incredibly fast and natural experience. In this talk, I will explain the why and the how of this method.
#### Learning objectives

See how we used Node to run hundreds of browser automation tests in seconds, without running a browser.
#### City of residence

Tel Aviv, Israel

**Comment by giltayar** [comment]
Slides: https://docs.google.com/presentation/d/13gPELVqP2YW1SSIjX_7rPkkmORhdwQH4GStTupao5XU

**Comment by gergelyke** [comment]
Hello Gil,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
