### ISSUE TITLE
A tale of one open-source contribution

### ISSUE THREAD

**Issue by naugtur** [nodeconf/budapest#55]
#### Title

A tale of one open-source contribution
#### Description

A story of how Max Ogden's suggestion, that I should use one library led to my humble self slowly becoming the maintainer.
#### Learning objectives

Learning that getting engaged in open-source is very rewarding and available to everyone thanks to how npm is rich in small, useful packages.
Seeing how casual contributions can lead to a great adventure.
#### City of residence

Poznań, Poland

**Comment by gergelyke** [comment]
Hello Zbyszek,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
