### ISSUE TITLE
Analyze your code - ESLint and TDD for custom static code analysis

### ISSUE THREAD

**Issue by danyshaanan** [nodeconf/budapest#56]
#### Title

Analyze your code - ESLint and TDD for custom static code analysis.
#### Description

While ESLint is often used with the set of rules that come bundled with it, this is often not enough. The true power of ESLint is that it is very easy to extend via custom rules.

This session will demonstrate how to use ESLint and its RuleTester to create your own custom analysis. During this session we will examine several different use cases, including building a game with ESLint rules.
#### Learning objectives

Learn how ESLint’s static analysis works and how to write custom rules.
#### City of residence

Tel Aviv.

**Comment by danyshaanan** [comment]
After reading https://github.com/nodeconf/budapest/issues/2, I understand that the focus might be better directed at the different use cases of static code analysis I have encountered, rather than on an actual demonstration of the technology.

**Comment by gergelyke** [comment]
Hello Dany,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
