### ISSUE TITLE
All roads lead to Amazon

### ISSUE THREAD

**Issue by andreicek** [nodeconf/budapest#57]
#### Title

All roads lead to Amazon
#### Description

We had to deal with an enormous amount of high definition images that had to be processed in a very short period while keeping the cost as low as possible at off-peak times. We went through a bunch of iterations, looked up various relevant services, services, and ended up with a working and stable product. Come and listen about strange bugs in production, pains on leveraging S3, SQS, and ECS, and learn from our mistakes. We are eager to share our success story with you!
#### Learning objectives
- A mess called Amazon documentation and pricing tables,
- How your local Docker installation is different from one in cloud,
- Fun with imagemagick (and why you should be looking for alternatives),
- And, testing everything. 
#### City of residence

Zagreb, Croatia

**Comment by gergelyke** [comment]
Hello Andrei,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
