### ISSUE TITLE
A Case for Integrity: JavaScript Apps Should Have it Too

### ISSUE THREAD

**Issue by JscramblerBlog** [nodeconf/budapest#58]
#### Title

A Case for Integrity: JavaScript Apps Should Have it Too
#### Description

JavaScript Web Applications are being used by virtually all tech companies in the world today, from startups to Fortune 500 organizations. Increasing amounts of logic are being shipped to the browser because of this. There is a need to interact with critical data such as user credentials, personally identifiable information, credit card numbers, etc - in other words, very sensitive information. Because JavaScript is highly dynamic, it's very easy to interfere with the apps behavior and its execution environment, thus there are risks that need to be addressed. In this talk we will discuss what is the current state of the art regarding the integrity of Web Applications on the client-side, show some attack scenarios. and how to avoid them.
#### Learning Objectives

Participants will know more about the integrity of Web Applications on the client-side, become aware of attack scenarios and ways to protect their Web Applications.
#### City of residence

Porto, Portugal

**Comment by gergelyke** [comment]
Hello Catarina,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
