### ISSUE TITLE
Offline: One Step Closer To Native Applications

### ISSUE THREAD

**Issue by yury-dymov** [nodeconf/budapest#59]
#### Offline: One Step Closer To Native Applications

![Keep Calm and survive with no network](https://habrastorage.org/files/574/ce5/d74/574ce5d74ff0495982e58a249d8d2062.jpg)
#### Description

The talk will help listeners to develop the offline-first mindset, which is a way to make applications work in all scenarios, not perfect ones. It will show, how to develop next level application, which supports both online and offline modes, and loads in new data whenever it is possible. This feature brings them to the same user experience level as native apps do. Users will still be able to work with the web application while being stuck in the no Internet zone or over-crowded conference.

Offline feature is still very experimental, so the practical example, which leverages [offline-plugin](https://github.com/NekR/offline-plugin) backed up by [sw-precache](https://github.com/GoogleChrome/sw-precache), [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox) will be shown with detailed explanation, how everything works under the hood and what issues developers might face.
#### Learning objectives
- Learn real-life use-cases, where offline support matters and how it can improve User Experience of your web applications
- Learn about [sw-precache](https://github.com/GoogleChrome/sw-precache), [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox) and [offline-plugin](https://github.com/NekR/offline-plugin) libraries
- Learn, how to integrate these tools in the existing project like a boss and get benefits right away
#### City of residence
1. I live in **Beijing, China** for one year now. 
2. In January I will be in the long business trip in Germany (Sankt Leon-Rot), which means that my travel costs are much lower. 
3. Originally I am from Moscow, Russia

**Comment by gergelyke** [comment]
Hello Yury,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
