### ISSUE TITLE
Demystifying JavaScript engines

### ISSUE THREAD

**Issue by a0viedo** [nodeconf/budapest#6]
#### Title

Demystifying JavaScript engines
#### Description

How a JavaScript engine works? What are its basic components? How to measure its performance? What is JIT compilation? Stigmatization: is JavaScript fast enough? are some of the questions I think we currently fail to answer in a, somewhat, short and direct way.
#### Learning objectives

It will be really useful for developers to know more about the underlying mechanisms that are being used to run their applications. Moreover, the talk will give attendees the concepts necessary to think on current performance bottlenecks and have some hints on how overcome them.
#### City of residence

Buenos Aires, Argentina

**Comment by gergelyke** [comment]
Hello Alejandro!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
