### ISSUE TITLE
Past, present and future of asynchronous JavaScript

### ISSUE THREAD

**Issue by DarkoKukovec** [nodeconf/budapest#60]
#### Title

Past, present and future of asynchronous JavaScript
#### Description

Asynchronous code execution was always among the main strengths of JavaScript. The fact that you don’t need to stop everything when you’re waiting for an external resource or event is a really powerful feature. The problem is: what’s the best way to handle the asynchronous part in order to avoid race conditions, pyramids of doom and spaghetti code? Through time, there were multiple solutions to this problem.
In this presentation, I’ll talk about the methods that were used before, methods that we can use today, and some methods that are not here yet, but once they become available, will make things much simpler.
#### Learning objectives
- Features supported in current node/browser implementations
- Libraries that can be used to make async easier
- Tools available to make async easier
- Features coming soon to the environment near you
#### City of residence

Zagreb, Croatia

**Comment by gergelyke** [comment]
Hello Darko,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
