### ISSUE TITLE
COPE with Node.js microservices

### ISSUE THREAD

**Issue by eduardoboucas** [nodeconf/budapest#61]
#### Title

COPE with Node.js microservices
#### Description

We live in a world where content is consumed in multifarious ways, with new channels and devices appearing every day. As a result, the tools traditionally used to author, publish and syndicate content are no longer the best choice, as they compromise the ability of your organisation to adapt at the pace that your audience demands.

This talk will describe how we can reinvent the web stack in support of the principle of COPE (Create Once, Publish Everywhere), focusing on an API-first, microservices approach, that is flexible, modular and scalable.

In an industry where organisations and engineers need to adapt to new technologies and concepts at an overwhelming pace, let's make sure your data management platform adapts with you, instead of slowing you down.
#### Learning objectives
- Modular services VS. monolithic CMS
- API-first mindset
- COPE
#### City of residence

London, England

**Comment by gergelyke** [comment]
Hello Eduardo,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
