### ISSUE TITLE
Break the Rules!

### ISSUE THREAD

**Issue by thebergamo** [nodeconf/budapest#62]
#### Title

Break the Rules
#### Description

Day after Day in the software development area, we've seen a lot of stacks emerging and dying, and these stacks become the major solutions for all your needs, and sometimes, ok, they are. But we need to understand the benefits and flaws of the stacks and open our mind to solve problems, not just build software with our favorite stacks. (I'm looking for you MEAN)
When someone looks to Node.js, they just have seen Node, MongoDB and Express, but we've a lot of others frameworks, databases to fit of your problem, is not a rule using this or that, or everything I will told you, because your problem is unique, the solution for your problem is unique and you need to meet the tools to do the job done right.
Give me the chance to show you how great is the Node.js ecosystem and new approaches for the old or new problems you will deal.
#### Learning objectives
- Open the mind of developers to solve the problems, not just apply the hype stack of software.
- Understand the Good and Bad about Node and your Ecosystem
- A little of software development to solve problems in the real world.
#### City of residence

São Paulo, Brazil

**Comment by gergelyke** [comment]
Hello Marcos,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
