### ISSUE TITLE
Self-improving software

### ISSUE THREAD

**Issue by bahmutov** [nodeconf/budapest#63]
#### Title

Self-improving software
#### Description

Every JavaScript project requires 3rd party modules. As soon as you depend on 
specific versions, your module falls behind. I will show how to keep your 
software up to date without any effort (as long as there are some tests). 
I will also show how your NPM package can guarantee NOT breaking its
downstream dependencies; and even the major changes can be upgraded
automatically by using code mods.
#### Learning objectives
- What is semver and why it matters
- How to keep your project up to date against its upstream dependencies
- How to release a new version without breaking every project that depends on it
- If you do need to release a new breaking version, how to write a code mod that
  will help every downstream dependency upgrade automatically.
#### City of residence

Boston

**Comment by gergelyke** [comment]
Hello Gleb,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
