### ISSUE TITLE
A checklist for your Node project

### ISSUE THREAD

**Issue by bahmutov** [nodeconf/budapest#64]
#### Title

A checklist for your Node project
#### Description

Checklists have been know to reduce errors during air flights and surgeries. 
Why don't we use one for our JavaScript projects?

I want my NPM module to be useful, robust, and well-documented. I want it to stand out
from the 100s of the modules that do a similar thing. Here is my recipe for a module
that everyone can rely on: a simple checklist. Rather than forcing everyone to do the same,
the checklist only reminds me to do unit testing, publish smaller module, have good
API examples, and lots of other useful things.
#### Learning objectives
- what should a solid Node project have from the very start: license, complete package.json,
  tests, readme, etc. I will show my checklist (available publicly) and will argue
  why each item is important.
- For each item there are alternative ways to implement it. A particular testing framework
  is not as important as having one.
- how to remove a pain of starting a project by using a generator
#### City of residence

Boston

**Comment by gergelyke** [comment]
Hello Gleb,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
