### ISSUE TITLE
Securing the front end, from a Node server

### ISSUE THREAD

**Issue by bahmutov** [nodeconf/budapest#65]
#### Title

Securing the front end, from a Node server
#### Description

A simple technique to disable the script injection attacks on your web pages is to disable
the inline JavaScript. This means that most popular ways to inject variables and code fragments
into your pages will have to change. I will show the JavaScript to JavaScript rendering
engine for Express that allows you to set very strict and safe Content-Security-Policy on
your website. Not only my approach is much safer, but it will be very testable as well.
#### Learning objectives
- Learn what are cross-site scripting attacks and why they are number 2 on the web application security project (OWASP) list of threats
- How Content-Security-Policy stops these attacks
- Why this technique is hard to implement (hint: variable injection from the server-side) and
  how to solve this.
#### City of residence

Boston

**Comment by gergelyke** [comment]
Hello Gleb,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
