### ISSUE TITLE
Streaming and Programming Nodebots over the web

### ISSUE THREAD

**Issue by mapmeld** [nodeconf/budapest#66]
#### Title

Streaming and Programming Nodebots over the web
#### Description

Everyone loves robots, but not everyone has an Arduino at home. This talk explains how to convert from software developer to hardware developer, and how to control an Arduino using NodeJS and Johnny-Five. We then build up the pieces of a remote robot-programming website: a video broadcast over WebRTC, a set of coding blocks from Google Blockly, and an Arduino-controlling server using the Johnny-Five and Node-Serial libraries.

This is based on three successful robot-streaming experiments which I ran on JustinTV and UStream before WebRTC was available
- CrowdBot (using Wiring and Python server) https://github.com/mapmeld/crowdbot
- CrowdBotBlock (NodeJS server and Blockly) https://github.com/mapmeld/crowdbotblock
- Noonniep (NodeJS server, Neo4j database, and Blockly) https://github.com/mapmeld/noonniep

I haven’t done a talk about these projects before.
#### Learning objectives
- WebRTC webcast
- Arduino with Johnny-Five
- Google Blockly block programming environment
#### City of residence

New York City, USA

**Comment by gergelyke** [comment]
Hello Nick,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
