### ISSUE TITLE
Think inside the box

### ISSUE THREAD

**Issue by bahmutov** [nodeconf/budapest#67]
#### Title

Think inside the box
#### Description

So you got a Nodejs server or a microservice. Now what? How do you deploy it without
pulling your hair? There are four products from the Ops world that I am excited about toda as a Node developer: Docker, Kubernetes, Dokku and Zeit. 
All make my life as a developer a lot simpler, plus they blur the line between the local and 
the production environments. Enterprises already use the first two, while every developer should use all four tools.
#### Learning objectives
- What is Docker and how to run a typical Node project inside the container securely
- How to quickly deploy a Node project using Zeit (great for micro services or smaller sites)
- How to have full control over the server and have additional services using Dokku
- Finally, how to control an army of servers using Kubernetes
#### City of residence

Boston

**Comment by gergelyke** [comment]
Hello Gleb,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
