### ISSUE TITLE
Stream JSON from Node.js to the DOM

### ISSUE THREAD

**Issue by pakastin** [nodeconf/budapest#68]
#### Description

I'm going to show from scratch how to stream big amount of JSON from node.js to the DOM so that you can start rendering the results as they come from the backend. It's easier than you might think.
#### Learning objectives
- Node.js Stream
- Using res.write and res.end instead of res.send (express.js)
- XMLHttpRequest (especially onprogress)
- Render buffer
#### City of residence

Finland

**Comment by pakastin** [comment]
Here's me giving a talk @ HelsinkiJS / Frontend Finland:
https://www.youtube.com/watch?v=0nh2EK1xveg

I started with node.js in 2011, still loving it everyday!

**Comment by gergelyke** [comment]
Hello Juha,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
