### ISSUE TITLE
command-line therapy

### ISSUE THREAD

**Issue by jebeck** [nodeconf/budapest#69]
#### Title

Command-line therapy 
#### Description

Node v0.11 introduced support for JavaScript ES2015 generator functions behind the harmony flag, and support without the flag landed in v4.0. But…perhaps you’re not using generators yet. That’s understandable: generators are _strange_, perhaps especially to those of us who came to programming through web development (i.e., JavaScript) and haven’t been exposed to multi-threaded systems. As proof of the strangeness of generators, let me offer this: it’s actually a best practice to stick a bunch of generator code inside of a `while (true)` loop, which I suspect is exactly the kind of `while` loop your first programming instructor told you scary stories about!

The disruption of the “normal” control flow that occurs with generators—functions that can be _paused_(!) during their execution—can feel a bit like turning your brain inside-out. In this talk, we’ll seek to understand generators through the metaphor of conversation, modeling the relationship between a generator function and its calling context as a turn-taking relationship, just like a (good) conversation. 

We’ll also find that we can take our metaphor literally and have a lot of **fun** with it: chatterbots are a natural application for generator functions. After starting with a simple gibberish bot that responds to user input, we’ll expand to a generator implementation of [Eliza](https://en.wikipedia.org/wiki/ELIZA) (everyone’s favorite therapist chat bot), so that our command line can be our therapist too.
#### Learning objectives

• concurrency basics
• JavaScript generator functions
• writing a simple interactive CLI with node
• a tiny bit of natural language processing theory
#### City of residence

Oakland, California (travel out of San Francisco)

**Comment by gergelyke** [comment]
Hello Jana,

**Comment by gergelyke** [comment]
Hello Jana,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
