### ISSUE TITLE
Building your next app in KoaJS and ES6/ES7

### ISSUE THREAD

**Issue by mapmeld** [nodeconf/budapest#7]
#### Title

Building your next app in KoaJS and ES6/ES7
#### Description

Using a photo-sharing app [1batch](https://github.com/mapmeld/1batch/wiki) as a template for making your next web app with the KoaJS framework.

At the beginning of 2016, I was surprised to see the thread [Is Express dying?](https://github.com/expressjs/express/issues/2844). All of my best apps are written in Express! So I went looking for a replacement.

[KoaJS](https://github.com/koajs/koa/blob/v2.x/Readme.md) (currently rolling out version 2) is a leading framework designed around the latest JS features, including arrow functions and replacing callbacks with async/await.  This talk would be targeted at Express users and new NodeJS programmers explaining how to use Koa, implement PassportJS to authenticate users, and compile code with BabelJS.
#### Learning objectives
- designing a simple mobile web app (Instagram clone)
- using KoaJS v2 framework
- async/await instead of callbacks or generators
- PassportJS authentication
- BabelJS transpiler
- compatibility with older Koa, Express, and other JS code
#### City of residence

New York City, USA

**Comment by gergelyke** [comment]
Hi Nick!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
