### ISSUE TITLE
Create your own fake DOM for node.js

### ISSUE THREAD

**Issue by pakastin** [nodeconf/budapest#70]
#### Description

I'm going to show how to create a fake DOM for node.js from scratch. It's useful for rendering frontend app in node.js for SEO or even to do some tests. Sounds harder than it really is. There are some implementations available, but they lack features or are too complex. This one is super simple.
#### Learning objectives
- document.createElement
- Document class
- classList
- textContent, set innerHTML, setAttribute
- appendChild, insertBefore
- get innerHTML, outerHTML
#### City of residence

Finland

**Comment by pakastin** [comment]
ps. I made two proposals for you to choose from, here's the another one: https://github.com/nodeconf/budapest/issues/68

What comes to the fake DOM, here's my implementation, which I'm going to write from scratch simplified in the talk: https://github.com/pakastin/nodom

Here's me giving a talk in HelsinkiJS / Frontend Finland:
https://www.youtube.com/watch?v=0nh2EK1xveg

**Comment by gergelyke** [comment]
Hello Juha,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
