### ISSUE TITLE
node.js Streams, :arrow_up: Level Up! 

### ISSUE THREAD

**Issue by lrlna** [nodeconf/budapest#71]
#### Title

node.js streams, :arrow_up: Level Up!
#### Description

Streams, you say, sure, I pipe in `bash` daily, and, hey, `stream.write()` and I are basically best friends. Although this little data type works quite a bit for us in the background, and we might use it regularly in our node projects, do we really know what's happening in the background?

Don't panic! I gotchu. Being a fan of debunking all the things happening in the background, in this talk, I'll walk you through what's happening behind the curtain of node.js with writables, readables, duplexes && transforms beyond the trusty `stream.pipe()`.
#### Learning objectives

I want the audience to walk away understanding more about the handling and creating streams in node.js, including memory management (where does it all go?). We are very used to working with various packages that handle data streaming for us (hello :wave: [through2](https://github.com/rvagg/through2), [pull-stream](https://github.com/pull-stream/pull-stream), [readable-stream](https://github.com/nodejs/readable-stream) and others) in the userland, but what could be happening under the hood is quite often a mystery. Let's make this a mystery no-more. 
#### City of residence

London, UK

**Comment by gergelyke** [comment]
Hello Irina,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
