### ISSUE TITLE
LETS BUILD A PEER TO PEER SYSTEM!

### ISSUE THREAD

**Issue by yoshuawuyts** [nodeconf/budapest#72]
### Title

LETS BUILD A PEER TO PEER SYSTEM!
#### Description

Ever wondered how peer to peer systems are implemented? In this talk we'll go
over how to implement a fully functional data exchange service from first
principles custom tailored for people new to the field. We'll go from a tiny
system with two nodes, up to something that can work at internet scale.  We'll
be touching on architecture, data structures, networking and more. At the end
of it you'll feel good about you, your coding abilities and your ability to p2p
in particular.
#### Learning objectives
- basic data structures used in p2p (mostly how kademlia works)
- an idea of which protocols are used in p2p, and why
- a sprinkle or architectural decision making
- feel confident you can peer to peer too :v:
#### City of residence

Berlin

**Comment by gergelyke** [comment]
Hello Yoshua,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
