### ISSUE TITLE
Universal rendering

### ISSUE THREAD

**Issue by sospedra** [nodeconf/budapest#74]
#### Title

Universal rendering with React
#### Description

How to proper server-side dispatch an SPA? You know about the benefits of SPAs. You want to use the top-notch techs like React, Redux, etc. But also you're concern about SEO, cache, loading speed, etc. We're not talking just about a code that can be run in any JS environment but a whole process. 

The client request a route. The server gets your SPA and gives it that route. Then the SPA hydrates itself according to the state-route binding. The server then returns the most basic HTML, inlined CSS and JS to run this specific and small part of your SPA. At this point the client is loaded and working nice; like a static one! Finally the SPA get the rest of the assets needed to became a proper SPA.

You're happy. Google is happy. The marketing team is happy. The servers are happy. Everyone is happy 👌🏽😁
#### Learning objectives

Isomorphic/Universal applications
perfMatters
Progressive webapps
#### City of residence

Barcelona

**Comment by gergelyke** [comment]
Hello Ruben,

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
