### ISSUE TITLE
Adding types to Javascript

### ISSUE THREAD

**Issue by vagmi** [nodeconf/budapest#8]
#### Description

In large codebases, it sometimes helps to have a compiler check for a few obvious errors to avoid them exploding at the users' faces at runtime. When I talk to other Javascript developers about static typing, they usually picture something like Java in their heads. The idea of this talk is to explore a few statically typed alternatives that you can use today to write better programs targeting both the browser and the server. To do this, we are going to look at three languages/libraries. We will walk through some of the defining features of these languages and explore the kind of bugs that these can catch in your codebase.
1. Flow - [Flow](https://flowtype.org/) is a static type checker for Javascript. It is not really a language but adds optional typing to your existing Javascript codebase. You can decorate your Javascript files with an `// @flow` comment as the first line and the flow will do the type checking for you. The output of the flow plugin is simply all the flow related parts stripped from the code. It plays quite well with babel so you could use any level of babel presets with Flow.
2. TypeScript - [TypeScript](https://www.typescriptlang.org/) is a statically typed language that compiles down to Javascript. Unlike flow, TypeScript is a compiler. You can also have typescript type annotations in a separate file accompanying your javascript file. While TS looks pretty much the same as Flow, it has slightly different semantics when it comes to handling generics and nullability.
3. PureScript - [PureScript](http://www.purescript.org/) is a strongly typed language that compiles down to Javascript. It is the deep end of the functional, strongly typed camp. While Flow and Typescript code still resembles Javascript, PureScript is closer to haskell. Purescript embraces immutability and forces you to organize your logic around pure functions with no side effects and couples that with a powerful monadic effect system. Unlike Elm, Purescript does not need a runtime and works well both on the server and the client. 
#### Learning objectives

The goal of this talk is to understand the landscape of statically typed compile-to-JS languages or checkers out there and how you can start using it today in your projects. While there are other worthy languages like [Dart](https://www.dartlang.org/), [Elm](http://elm-lang.org/), [Ceylon](http://ceylon-lang.org/) or [Kotlin](https://kotlinlang.org/) I am focusing on these three languages because I only have 20 minutes and I like these languages.
#### City of residence

I am residing in [Chennai, India](https://www.google.co.in/maps/@13.0475255,80.2090117,11z). You can view some of my other [talks on youtube](https://www.youtube.com/playlist?list=PLVbkwm50L3Yxy2LcthD8ln3JfvWVdF7Am).

**Comment by gergelyke** [comment]
Hey there!

We really, really thank you for your participation in the Call for Proposal for NodeConf Budapest 2017!

We're sorry to tell you, that although your topic was really great, it didn't get accepted to our event this year. It wasn't an easy decision, and it took a while for us, but with all the factors that influenced us during the selection process, it had to be made.

To compensate this sad news a bit, we would like to invite you to come as an attendee! As an appreciation for the effort you already made to make this event great, we'd like to give you a ticket with a 20% discount: 
https://ti.to/risingstack/nodeconf-budapest/discount/thanks-for-your-cfp

We hope you can make it!
