### ISSUE TITLE
debugging < profiling < monitoring < tracing

### ISSUE THREAD

**Issue by danielkhan** [nodeconf/budapest#9]
#### Title

debugging < profiling < monitoring < tracing
#### Description

For each stage of your applications lifecycle there are viable ways to get insights into Node.js.
But what happens if we attach a debugger or what does the V8 profiling facility give us and what does it cost and what makes tracing Node so hard to do? 
Let's run through the various metrics available to learn when to use which and find out what's on the slate for upcoming versions of Node.
#### Learning objectives
- Get to know the metrics Node.js provides
- Learn to interpret them
- Understand the theory behind them
#### City of residence

Linz / Austria

**Comment by gergelyke** [comment]
Hello Daniel,

closing this, as your other submission was selected!
